version: "3.8"

services:
  database-rentacar:
    image: postgres
    container_name: database-rentacar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rentacar
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentacar-server
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata: